# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197VKITEfhPVu34GPtgSVmRrVZIlXZEEY
"""

li = ['abc', 23, 4.34, 23]
li[1]=45
li

t = (23, 'abc', 4.56, (2,3), 'def')
t[2]=3.14
t
>>>error

li = [1, 11, 3, 4, 5]
li.append('a') # Note the method syntax
li

li.insert(2, 'i')
li

li.extend([9, 8, 7]) 
li

li.append([10, 11, 12])
li

li = ['a', 'b', 'c', 'b']
li.index('b') # index of first occurrence*
li.count('b') # number of occurrences
li.remove('b') # remove first occurrence
li

li = [5, 2, 6, 8]
li.reverse() # reverse the list *in place*
li
li.sort() # sort the list *in place*
li
li.sort(some_function) 
# sort in place using user-defined comparison