# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uewf13Wq65cxQhSG4yw7UCy1ulYhVDrn
"""

for <item> in <collection>:
  <statements>

for someChar in "Hello World":
  print (someChar)

for <item> in <collection>:
  <statements>

for (x, y) in [(a,1), (b,2), (c,3), (d,4)]:
  print (x)

for x in range(5):
  print (x)

for i in range(len(mylist)):
  print (i, mylist[i])

for (i, item) in enumerate(mylist):
  print (i, item)

