# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OJJ0W79HOf8Cx7JDCE97EoBEG-ZDZAIa
"""

x=3
if x == 3:
  print ("X equals 3.")
elif x == 2:
  print ("X equals 2.")
else:
  print ("X equals something else.")
print ("This is outside the ‘if’.")

x = 3
while x < 5:
  print (x, "still in the loop")
  x = x + 1

x = 6
while x < 5:
  print (x, "still in the loop")

