# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fEAK_r7AB633lBqgoUzabNtP1mD-1qxQ
"""

li = [3, 6, 2, 7]
[elem*2 for elem in li]

li = [('a', 1), ('b', 2), ('c', 7)]
[ n * 3 for (x, n) in li]

li = [3, 6, 2, 7, 1, 9]
[elem * 2 for elem in li if elem > 4]

li = [3, 2, 4, 1]
[elem*2 for elem in [item+1 for item in li] ]

