# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17RZg4xY2HecP5-CrGD58aYLYJ6KOIcKG
"""

d = {'user':'bozo', 'pswd':1234}
d['user'] 
d['pswd']
d['bozo']

d = {'user':'bozo', 'pswd':1234}
d['user'] = 'clown'
d
d['id'] = 45
d

d = {'user':'bozo', 'p':1234, 'i':34}
del d['user']# Remove one. Note that del is
# a function.
d
d.clear() # Remove all.
d
a=[1,2]
del a[1] # (del also works on lists)
a

d = {'user':'bozo', 'p':1234, 'i':34}
d.keys()  # List of current keys
d.values() # List of current values.
d.items() # List of item tuples.

