# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mBBJlsvXzUlYxhQd-Pa5eh_LUv-CwmYz
"""

x = 34 - 23 # A comment.
y = "Hello" # Another one.
z = 3.45 
if z == 3.45 or y == "Hello":
  x = x + 1
  y = y + "World" # String concat.
print (x)
print (y)

tu = (23, 'abc', 4.56, (2,3), 'def')
li = ["abc", 34, 4.34, 23]
st = "Hello World"
st = 'Hello World'
st = """This is a multi-line
string that uses triple quotes."""

tu = (23, 'abc', 4.56, (2,3), 'def')
tu[1]

li = ["abc", 34, 4.34, 23]
li[1]

st = "Hello World"
st[1]

t = (23, 'abc', 4.56, (2,3), 'def')
t[-3]

t = (23, 'abc', 4.56, (2,3), 'def')
t[1:4]

t = (23, 'abc', 4.56, (2,3), 'def')
t[1:-1]

t = (23, 'abc', 4.56, (2,3), 'def')
t[1:-1:2]

t = (23, 'abc', 4.56, (2,3), 'def')
t[:2]

t = (23, 'abc', 4.56, (2,3), 'def')
t[2:]

t = (23, 'abc', 4.56, (2,3), 'def')
t[:]

t = [1, 2, 4, 5]
3 in t

4 in t

4 not in t

a='abcde'
'c' in a

'cd' in a

'ac' in a

(1, 2, 3) + (4, 5, 6)

[1, 2, 3] + [4, 5, 6]

"Hello"+""+"World"

