# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gaCEaRlIwG4Pri_-rW-zWIwxCu5hmIPJ
"""

X == Y
X is Y :

a and b
a or b
not a
x = true_value if condition else false_value

