# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mBBJlsvXzUlYxhQd-Pa5eh_LUv-CwmYz
"""

x = 34 - 23 # A comment.
y = "Hello" # Another one.
z = 3.45 
if z == 3.45 or y == "Hello":
  x = x + 1
  y = y + "World" # String concat.
print (x)
print (y)